agents:
    trae_agent:
        enable_lakeview: true
        model: trae_agent_model
        # max_steps: 200
        max_steps: 20
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done
allow_mcp_servers:
    - playwright
mcp_servers:
    playwright:
        command: npx
        args:
            - "@playwright/mcp@0.0.27"
lakeview:
    model: lakeview_model

model_providers:
    anthropic:
        api_key: your_anthropic_api_key
        provider: anthropic
    ollama:
        api_key: ollama
        base_url: http://localhost:11434/v1
        provider: ollama

models:
    trae_agent_model:
        model_provider: ollama
        model: qwen2.5-coder:0.5b
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
    lakeview_model:
        model_provider: ollama
        model: qwen2.5-coder:0.5b
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
